pytest

diff --git a/.github/workflows/build_and_validate.yml b/.github/workflows/build_and_validate.yml
--- a/.github/workflows/build_and_validate.yml
+++ b/.github/workflows/build_and_validate.yml
@@ -46,7 +46,12 @@ jobs:
         run: pip install -r requirements-dev.txt
 
       - name: Run pytest
-        run:  pytest --max-failure-rate 0.5 -n 4 -v --cov --cov-report xml:coverage.xml ${GITHUB_WORKSPACE}/tests
+        run:  |
+          pytest --max-failure-rate 0.5 -n 4 -v --cov --cov-report xml:coverage.xml ${GITHUB_WORKSPACE}/tests || true
+          if [ $TEST_SUITE_FAILURE -eq 1 ]; then
+              echo "Tests failed"
+              exit 1
+          fi
 
       - name: Get Cover 
         uses: orgoro/coverage@v3.1
